### PR TITLE
Handle redirect urls and unbounded positional arguments

### LINKED ISSUE #27: Installer download fails when download URLs are HTTP redirects
# Brief description of your issue

The tool does not process download URLs that are redirects to another URL.

# Steps to reproduce

Run `winget new` and enter URL `https://download.qt.io/official_releases/qtcreator/4.15/4.15.0/qt-creator-opensource-windows-x86_64-4.15.0.exe`

# Expected behavior

The tool should follow the redirect (but insert the original URL in the manifest).

# Actual behavior

The tool fails with error
```
Failed to download installer.
HTTP response was unsuccessful. Status code: Redirect
```

# Environment

```none
Windows Manifest Creator v0.1.0.1
```

### LINKED ISSUE #89: Update Command does not show warning when forgetting to include --url flag.
Update command fails to show the user an error message when they forget to include the --url flag when specifying the installer URL. 

Expected behavior:
Show an error message to include the flag or that the format of the parameter is incorrect.

### PR DESCRIPTION
**Pull request by ryfu-msft**
This pull request addresses the following issues:
Fixes #89 
Fixes #27 

Changes:
- Allows for redirect urls to be downloaded and parsed. The maximum number of redirects is 2.
- Adds additional hidden parameter that captures all unbound parameters after the first positional argument in the update and submit command. This is used to check if any invalid parameters are included and let the user know if they might have forgotten to include a flag.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-create/pull/104)

### CODE REVIEW

File: src/WingetCreateCLI/Commands/SubmitCommand.cs [hunk 1]
```diff
@@ -57,6 +63,13 @@ public override async Task<bool> Execute()
 
             try
             {
+                if (this.UnboundArgs.Count() > 0)
```
Comment (palenshus) [inline src/WingetCreateCLI/Commands/SubmitCommand.cs:66]: >.Count() > 0 [](http://example.com/codeflow?start=36&length=12)

.Any()

File: src/WingetCreateTests/WingetCreateTests/UnitTests/UpdateCommandTests.cs [hunk 2]
```diff
@@ -82,7 +82,7 @@ public async Task UpdateCommandGitHubManifestTest()
         /// Tests the <see cref="UpdateCommand.DeserializeExistingManifestsAndUpdate"/> command, ensuring that it updates properties as expected.
         /// </summary>
         /// <returns>A <see cref="Task"/> representing the result of the asynchronous operation.</returns>
-        //[Test]
```
Comment (palenshus) [inline src/WingetCreateTests/WingetCreateTests/UnitTests/UpdateCommandTests.cs:85]: Can you try uncommenting this and see if it still repros? I suspect it's intermittent, and instead of commenting out the test we should let it fail to give us pain to fix it

**Review by palenshus — CHANGES_REQUESTED** [review]
:clock1:

File: src/WingetCreateTests/WingetCreateTests/UnitTests/UpdateCommandTests.cs (hunk 2 above)
Comment (ryfu-msft) [reply src/WingetCreateTests/WingetCreateTests/UnitTests/UpdateCommandTests.cs:85]: commented it out, lets see what happens

File: src/WingetCreateCLI/Commands/SubmitCommand.cs (hunk 1 above)
Comment (ryfu-msft) [reply src/WingetCreateCLI/Commands/SubmitCommand.cs]: keep forgetting that this exists 🤦

**Comment by palenshus** [comment]
>         public const string TestMsixManifest = "WingetCreateE2E.MsixTest.yaml";

Why is this back?

---
Refers to: src/WingetCreateTests/WingetCreateTests/TestConstants.cs:69 in 8d84419. [](commit_id = 8d844193d817958a031e0441d194233eb6d9f57a, deletion_comment = False)

File: src/WingetCreateTests/WingetCreateTests/UnitTests/UpdateCommandTests.cs (hunk 2 above)
Comment (palenshus) [reply src/WingetCreateTests/WingetCreateTests/UnitTests/UpdateCommandTests.cs:85]: Looks like it passed

**Comment by ryfu-msft** [comment]
> > ```
> >     public const string TestMsixManifest = "WingetCreateE2E.MsixTest.yaml";
> > ```
> 
> Why is this back?
> 
> Refers to: src/WingetCreateTests/WingetCreateTests/TestConstants.cs:69 in [8d84419](https://github.com/microsoft/winget-create/commit/8d844193d817958a031e0441d194233eb6d9f57a). [](commit_id = [8d84419](https://github.com/microsoft/winget-create/commit/8d844193d817958a031e0441d194233eb6d9f57a), deletion_comment = False)

I had to reset some files, but you're probably referencing an old commit. It shouldn't be there.

File: src/WingetCreateCore/Common/PackageParser.cs [hunk 3]
```diff
@@ -100,6 +100,14 @@ public static async Task<string> DownloadFileAsync(string url, long? maxDownload
         {
             var response = await httpClient.GetAsync(url, HttpCompletionOption.ResponseHeadersRead);
 
+            int redirectCount = 0;
+            while (response.StatusCode == System.Net.HttpStatusCode.Redirect && redirectCount < 2)
+            {
+                var redirectUri = response.Headers.Location;
+                response = await httpClient.GetAsync(redirectUri, HttpCompletionOption.ResponseHeadersRead);
+                redirectCount++;
+            }
```
Comment (chausner) [inline src/WingetCreateCore/Common/PackageParser.cs:109]: HttpClientHandler has https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.allowautoredirect?view=net-5.0. It's enabled by default already so I wonder why it does not follow redirects out-of-the-box.

Comment (palenshus) [reply src/WingetCreateCore/Common/PackageParser.cs:109]: It doesn't redirect automatically for https->http redirects

Comment (palenshus) [reply src/WingetCreateCore/Common/PackageParser.cs:109]: Here's a simple LINQPad query repro: http://share.linqpad.net/aup4og.linq. You can uncomment the lines to see our fix

**Review by palenshus — APPROVED** [review]

File: src/WingetCreateTests/WingetCreateTests/TestConstants.cs [hunk 4]
```diff
@@ -48,11 +48,6 @@ public static class TestConstants
         /// </summary>
         public const string TestMsiPackageIdentifier = "WingetCreateE2E.MsiTest";
 
-        /// <summary>
-        /// PackageIdentifier for test msix.
-        /// </summary>
-        public const string TestMsixPackageIdentifier = "WingetCreateE2E.MsixTest";
```
[the remark this answers is not in the document]
Comment (ryfu-msft) [reply src/WingetCreateTests/WingetCreateTests/TestConstants.cs:54]: removed
