### PR TITLE
Handle taskcanceled exception with error message

### LINKED ISSUE #197: Unclear exception after timeout while downloading an installer
### Description of the new feature / enhancement

The error now just says "Couldn't download an installer" and spits out stack trace.

I think it would be better to explicitly say that timout happened, rather than make user try to read the trace, or add an option to extend the timeout duration.

Now it looks like this:
image

### Proposed technical implementation details

_No response_

### PR DESCRIPTION
**Pull request by ryfu-msft**
Fixes #197 

Changes
- Handles the exception that's thrown when the download request fails due to timeout.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-create/pull/201)

### CODE REVIEW

File: src/WingetCreateCLI/Commands/BaseCommand.cs [hunk 1]
```diff
@@ -305,6 +305,12 @@ protected static async Task<string> DownloadPackageFile(string installerUrl)
                     return null;
                 }
 
+                if (e is TaskCanceledException)
```
Comment (palenshus) [inline src/WingetCreateCLI/Commands/BaseCommand.cs:308]: For clarity can you make these all if-else blocks?

**Review by palenshus — APPROVED** [review]

File: src/WingetCreateCLI/Commands/BaseCommand.cs (hunk 1 above)
Comment (ryfu-msft) [reply src/WingetCreateCLI/Commands/BaseCommand.cs]: Added else-if blocks for clarify

**Review by palenshus — APPROVED** [review]

**Review by mohmadalabdalui — COMMENTED** [review]
``
