### PR TITLE
Make direct API call to sync fork

### LINKED ISSUE #579: Failing to submit manifests
### Brief description of your issue

Unable to submit manifests

### Steps to reproduce

Run `wingetcreate update Cilium.CiliumCLI -s -v 0.16.23 -u https://github.com/cilium/cilium-cli/releases/download/v0.16.23/cilium-windows-amd64.zip https://github.com/cilium/cilium-cli/releases/download/v0.16.23/cilium-windows-arm64.zip -t <github token>`

### Expected behavior

It should submit the PR for new version

### Actual behavior

Fails and throws this error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.GitHubSubmitManifests(Manifests manifests, String prTitle, Boolean shouldReplace, String replaceVersion)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.ExecuteManifestUpdate(List`1 latestManifestContent, CommandExecutedEvent commandEvent)
   at Microsoft.WingetCreateCLI.Commands.UpdateCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```

### Environment

```shell
Windows Package Manager Manifest Creator v1.9.3.0
Copyright (c) Microsoft Corporation. All rights reserved.

Operating System: Microsoft Windows NT 10.0.26100.0
System Architecture: X64
```

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?
	- Resolves https://github.com/microsoft/winget-create/issues/580
  - Resolves #579

This should _hopefully_ also address https://github.com/microsoft/winget-create/issues/502 as we won't be using Octokit Git API anymore to sync fork

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-create/pull/581)

### CODE REVIEW

**Comment by Trenly** [comment]
cc @AmelBawa-msft

File: src/WingetCreateCore/Common/GitHub.cs [hunk 1]
```diff
@@ -483,8 +486,23 @@ private async Task UpdateForkedRepoWithUpstreamCommits(Repository forkedRepo)
...
+                httpClient.DefaultRequestHeaders.Add("X-GitHub-Api-Version", "2022-11-28");
+                httpClient.DefaultRequestHeaders.UserAgent.TryParseAdd(Constants.ProgramName);
+
+                // Payload
+                JsonObject jsonObject = new JsonObject { { "branch", forkedRepo.DefaultBranch } };
+                var content = new StringContent(jsonObject.ToString(), Encoding.UTF8, "application/json");
+
+                var url = $"https://api.github.com/repos/{forkedRepo.Owner.Login}/{forkedRepo.Name}/merge-upstream";
+                var response = await httpClient.PostAsync(url, content);
+                response.EnsureSuccessStatusCode();
```
Comment (Trenly) [inline src/WingetCreateCore/Common/GitHub.cs:505]: Since the API provides a specific status code for a merge conflict, should there be special handling for the error status codes? Right now this will simply throw the error and exit, but it could be nice to know that `The forked repository could not be synced due to a merge conflict on the default branch` if the response code is `409`

Comment (mdanish-kh) [reply src/WingetCreateCore/Common/GitHub.cs:505]: We can and I thought of emitting custom exceptions.. but given the blast radius here I didn't want to introduce any resource strings in this PR that could delay getting this checked in as a hotfix.

Comment (Trenly) [reply src/WingetCreateCore/Common/GitHub.cs:505]: Fair enough; No complaints from me

Comment (mdanish-kh) [reply src/WingetCreateCore/Common/GitHub.cs:505]: And also, I'm guessing a merge conflict would only ever arise if the fork is ahead of the upstream branch, and for that case the flow would never reach here since it's handled above in

https://github.com/microsoft/winget-create/blob/60cc6f2a8e1613574043cab64fe8767e91dd369d/src/WingetCreateCore/Common/GitHub.cs#L480-L484

File: src/WingetCreateCore/Common/GitHub.cs [hunk 2]
```diff
@@ -483,8 +486,23 @@ private async Task UpdateForkedRepoWithUpstreamCommits(Repository forkedRepo)
                     throw new NonFastForwardException(commitsAheadBy);
                 }
 
-                var upstreamBranchReference = await this.github.Git.Reference.Get(upstream.Id, $"heads/{upstream.DefaultBranch}");
-                await this.github.Git.Reference.Update(forkedRepo.Id, $"heads/{forkedRepo.DefaultBranch}", new ReferenceUpdate(upstreamBranchReference.Object.Sha));
+                // Octokit .NET doesn't support sync fork endpoint, so we make a direct call to the GitHub API.
```
Comment (AmelBawa-msft) [inline src/WingetCreateCore/Common/GitHub.cs:489]: Great find! Thank you. What is an appropriate github/doc link to add to this comment here so we can continue leveraging the Github API (Octokit .net) once this issue is resolved? Or that change was by design?

Comment (mdanish-kh) [reply src/WingetCreateCore/Common/GitHub.cs:489]: I created an issue myself for this request - which I can add a link to in the comment.

- https://github.com/octokit/octokit.net/issues/2989

**Review by AmelBawa-msft — APPROVED** [review]

File: src/WingetCreateCore/Common/GitHub.cs (hunk 2 above)
Comment (AmelBawa-msft) [reply src/WingetCreateCore/Common/GitHub.cs:489]: Awesome! I appreciate it. Adding the comment will help us remember to change this in the future 😊

File: src/WingetCreateCore/Common/GitHub.cs (hunk 1 above)
Comment (AmelBawa-msft) [reply src/WingetCreateCore/Common/GitHub.cs:506]: Is this ok to resolve?

Comment (mdanish-kh) [reply src/WingetCreateCore/Common/GitHub.cs:506]: Yep! Okay from me @AmelBawa-msft

**Review by 3b123 — APPROVED** [review]
