### PR TITLE
Fix null/empty filename string when downloading package file

### LINKED ISSUE #292: Installer URIs being a redirect cause a `System.UnauthorizedAccessException`
### Brief description of your issue

When I supply an Installer URI that is a redirect to the actual download link, I get the `System.UnauthorizedAccessException` as shown below.

### Steps to reproduce

1. run `wingetcreate new`
1. Supply `https://www.two-notes.com/download/76391/` as installer url (it is the Windows / x64 installer from https://www.two-notes.com/en/torpedo-series/torpedo-remote/)

### Expected behavior

winget-create follows the redirect and downloads the installer from the correct path.

### Actual behavior

```
Downloading and parsing: https://www.two-notes.com/download/76391/...
Failed to download installer.
System.UnauthorizedAccessException: Access to the path 'C:\Users\HansBakker\AppData\Local\Temp\wingetcreate' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.WingetCreateCore.PackageParser.DownloadFileAsync(String url, Nullable`1 maxDownloadSize)
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.DownloadPackageFile(String installerUrl)
   at Microsoft.WingetCreateCLI.Commands.NewCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
```
image

### Environment

```shell
Windows Package Manager v1.2.11601
Windows: Windows.Desktop v10.0.22000.795
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

### PR DESCRIPTION
**Pull request by ryfu-msft**
Fixes #292 

The changes in this PR fix an issue where the target filename used to create the package file is null. This can cause an UnauthorizedAccessException since an empty filename means that the File.OpenWrite is trying to write to a directory instead of a file. To resolve this, I use the filename from the requestUrl as the last option for the filename in case both the contentDispositionFile and urlFile names are both empty. 

Verified manually with the related issue.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-create/pull/293)

### CODE REVIEW

File: src/WingetCreateCore/Common/Extensions.cs [hunk 1]
```diff
@@ -93,6 +93,16 @@ public static string ToEnumAttributeValue(this Enum enumVal)
...
             EnumMemberAttribute attributeValue = (attributes.Length > 0) ? (EnumMemberAttribute)attributes[0] : null;
             return attributeValue?.Value ?? enumVal.ToString();
+        }
+
+        /// <summary>
+        /// Returns null if the target string is empty.
+        /// </summary>
+        /// <param name="s">Target string value.</param>
+        /// <returns>Null if the string is empty; otherwise the original string value.</returns>
+        public static string NullIfEmpty(this string s)
```
Comment (yao-msft) [inline src/WingetCreateCore/Common/Extensions.cs:103]: Is this common practice?

**Review by yao-msft — APPROVED** [review]

File: src/WingetCreateCore/Common/Extensions.cs (hunk 1 above)
Comment (ryfu-msft) [reply src/WingetCreateCore/Common/Extensions.cs:103]: I believe it is, since it is commonly used with the null coalescing operator when handling empty strings
